# Generated by Django 5.2.6 on 2025-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('classroom', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='M', max_length=1)),
                ('study_status', models.CharField(choices=[('A', 'Đang học'), ('N', 'Nghỉ học'), ('S', 'Đã tốt nghiệp')], default='A', max_length=1)),
                ('academic', models.CharField(choices=[('G', 'Giỏi'), ('K', 'Khá'), ('TB', 'Trung bình'), ('Y', 'Yếu')], default='TB', max_length=3)),
                ('score', models.FloatField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_note', models.TextField(blank=True, default='Không có ghi chú')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Đã đóng'), ('unpaid', 'Chưa đóng'), ('partial', 'Đóng một phần')], default='unpaid', max_length=10)),
            ],
        ),
    ]
